/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:ac8c6a13-c235-4e96-b790-0b023871fd52",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_dhnELOjI3",
    "aws_user_pools_web_client_id": "q1fa2a6j0r759hf1l5mas7roa",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://ibk35rnouzdedeoc4craoohpba.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
